In the next example we will get slightly more sophisticated and introduce a JPA-QL query. Using JPQ-QL queries within Data Services
has a few valuable advantages. HQL allows for more complicated queries. Typing is enabled, along with compile time
checking with HQL queries. Finally, HQL within Data Services safeguards against SQL injection attacks.

Create a query that searches people by state. Given a state, find all the people that live there.  Furthermore, introduce business logic
that calculates the average age of people living in state.

We will place this in a new class `PersonLocationService`.

[source, groovy]
.grails-app/services/example/grails/PersonLocationService.groovy
----
include::{sourceDir}/grails-app/services/example/grails/PersonLocationService.groovy[]
----

<1> `@Query` used to define HQL.
<2> Typing of `Person` enabled.
<3> `state` param can be used within the HQL query.
<4> Business logic is implemented in the public method, which will be marked with transactional boundaries by GORM.
<5> Invocation of `searchByState` which is automatically implemented by GORM.

Use another integration test to make sure the Data Service is correct, along with the business logic

[source, groovy]
.src/integration-test/groovy/example/grails/PersonLocationServiceIntSpec.groovy
----
include::{sourceDir}/src/integration-test/groovy/example/grails/PersonLocationServiceIntSpec.groovy[]
----